### PR TITLE
Use project template + initialize config

### PR DESCRIPTION
**Pull request by febo**
This PR applies the [create solana program](https://github.com/solana-program/create-solana-program) template to the stake program.

It also has an initial implementation of `initialize_config` and `update_config` instructions.

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
Compared to our checks in SPL, the CI could use a few additional things:

* a configured nightly rust compiler
* cargo audit on program and rust client
* cargo fmt --check on program and rust client (requires nightly rust)
 * cargo clippy on the program, along with additional args like `-Zunstable-options --all-targets --features bpf-entrypoint,test-sbf -- --deny=warnings --deny=clippy::arithmetic_side_effects` (also requiring nightly)

https://github.com/paladin-bladesmith/paladin-rewards-program/pull/5 has the important elements for the program, but doesn't use the overall layout for the generated repo

**Comment by febo** [comment]
The PR is ready for a first review. There are a few of things that I would like to discuss:
1. I am using the `spl-pod` crate for the `Config` account fields, which means that the account is "hybrid" since not all types are fully zero-copy. It was needed since there is a `u16` field on the account; also, I added a discriminator (`u8`) and a bump (`u8`) for the vault signer. We could "bundle" these values together into a `data: [u8; 8]` field to have everything aligned to 8 bytes and add accessor methods for these 3 fields; or we could replace them and make the account 8 bytes aligned; or we could leave as it is.
2. I am not sure that we need to use `OptionalNonZeroPubkey` for the `slash_authority` – would there be a case where slash would be disable by setting this authority to `None`?
3. Do we need to validate the input for `cooldown_time_seconds` and `max_deactivation_basis_points` on the initialize and update?

I added a validation for a transfer hook but I am not using the Rewards program id there yet. I am guessing that at some point we will have a crate dependency to the Rewards program so we can get the program id from there.

**Comment by febo** [comment]
> Compared to our checks in SPL, the CI could use a few additional things:
> 
> * a configured nightly rust compiler
> * cargo audit on program and rust client
> * cargo fmt --check on program and rust client (requires nightly rust)
> * cargo clippy on the program, along with additional args like `-Zunstable-options --all-targets --features bpf-entrypoint,test-sbf -- --deny=warnings --deny=clippy::arithmetic_side_effects` (also requiring nightly)
> 
> [paladin-bladesmith/paladin-rewards-program#5](https://github.com/paladin-bladesmith/paladin-rewards-program/pull/5) has the important elements for the program, but doesn't use the overall layout for the generated repo

Spoke to @buffalojoec about this and we will make the change to the `create-solana-program` and then port it here, most likely on a separate PR.

**Comment by joncinque** [comment]
Sorry, this PR has become really huge and difficult to parse, would it be possible to split this up? From what I see, this has a few separate bits:

* conversion to shank + IDL
* addition of all create-solana-program generated clients, scripts, and CI
* initialize_config implementation
* update_config implementation
* some changes to state and instruction types?

Or if there's another way to present this, I'm game!

**Comment by febo** [comment]
> Sorry, this PR has become really huge and difficult to parse, would it be possible to split this up? From what I see, this has a few separate bits:
> 
> * conversion to shank + IDL
> * addition of all create-solana-program generated clients, scripts, and CI
> * initialize_config implementation
> * update_config implementation
> * some changes to state and instruction types?
> 
> Or if there's another way to present this, I'm game!

Agree, I will close this PR and create a new one with separate commits for:
* `create-solana-program` template
* shank annotation for instructions
* account types

Then create a separate PRs for each instruction:
* `initialize_config`
* `update_config`

**Pull request closed without merging**
